# Generated by Django 3.0.6 on 2020-05-14 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200514_0316'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address_line_2',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
