# Generated by Django 3.0.6 on 2020-05-25 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200520_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(max_length=200, null=True, upload_to=''),
        ),
    ]
