# Generated by Django 3.0.6 on 2020-05-16 05:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_user_is_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='collection_id',
            field=models.CharField(default=uuid.UUID('2a82a858-afc2-4c43-b7ae-6c6770f6d7d2'), max_length=50, null=True),
        ),
    ]
