# Generated by Django 3.0.6 on 2020-05-16 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_collection_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='collection_id',
            field=models.CharField(default='123', max_length=50, null=True),
        ),
    ]
