# Generated by Django 3.0.6 on 2020-05-16 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20200516_0608'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='id_coll',
        ),
        migrations.AddField(
            model_name='user',
            name='collection_id',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
