# Generated by Django 3.0.6 on 2020-05-16 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20200516_0614'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='collection_id',
        ),
    ]
