# Generated by Django 3.0.6 on 2020-06-02 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20200513_0504'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='for_sale',
        ),
        migrations.RemoveField(
            model_name='book',
            name='price',
        ),
    ]
