# Generated by Django 3.0.6 on 2020-06-02 03:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('digital_books', '0007_auto_20200527_2137'),
    ]

    operations = [
        migrations.CreateModel(
            name='DigitalBookPDF',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf', models.FileField(upload_to='')),
                ('book', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='digital_books.Digital_Book')),
            ],
        ),
    ]
