# Generated by Django 3.0.6 on 2020-06-03 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50)),
                ('card_holder', models.CharField(max_length=50)),
                ('card_number', models.CharField(max_length=50)),
                ('exp_date', models.CharField(max_length=50)),
            ],
        ),
    ]
