# Generated by Django 3.0.6 on 2020-05-14 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Magazine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=50)),
                ('volume', models.CharField(max_length=50)),
                ('release_date', models.DateField()),
                ('number', models.CharField(max_length=25)),
                ('quantity', models.PositiveIntegerField()),
            ],
        ),
    ]
