# Generated by Django 3.0.6 on 2020-05-30 03:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('digital_books', '0007_auto_20200527_2137'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('electronicbookcollections', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='electronicbookcollection',
            name='collection_id',
        ),
        migrations.AddField(
            model_name='electronicbookcollection',
            name='digital_books',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='digital_books.Digital_Book'),
        ),
        migrations.AddField(
            model_name='electronicbookcollection',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
