# Generated by Django 3.0.6 on 2020-06-02 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('electronicbookcollections', '0008_auto_20200602_0209'),
        ('electronicbookcollections', '0010_auto_20200602_0642'),
    ]

    operations = [
    ]
