# Generated by Django 3.0.6 on 2020-06-02 15:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('magazines', '0003_auto_20200531_0056'),
        ('magazinecollections', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='magazinecollection',
            name='collection_id',
        ),
        migrations.AddField(
            model_name='magazinecollection',
            name='description',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='magazinecollection',
            name='magazine',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='magazines.Magazine'),
        ),
        migrations.AddField(
            model_name='magazinecollection',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
