# Generated by Django 3.0.6 on 2020-06-02 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0022_auto_20200602_0642'),
        ('inventories', '0020_auto_20200602_0209'),
    ]

    operations = [
    ]
