# Generated by Django 3.0.6 on 2020-06-02 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='activity',
            field=models.CharField(default='', max_length=50),
        ),
    ]
