# Generated by Django 3.0.6 on 2020-05-27 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital_books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='digital_book',
            name='cover',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
