# Generated by Django 3.0.6 on 2020-05-27 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital_books', '0002_digital_book_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='digital_book',
            name='release_date',
            field=models.DateField(),
        ),
    ]
