# Generated by Django 3.0.6 on 2020-05-27 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital_books', '0003_auto_20200527_0113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='digital_book',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=2),
        ),
    ]
