# Generated by Django 3.0.6 on 2020-05-27 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital_books', '0004_auto_20200527_0115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='digital_book',
            name='price',
            field=models.DecimalField(decimal_places=4, max_digits=4),
        ),
    ]
