# Generated by Django 3.0.6 on 2020-05-27 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0001_initial'),
        ('digital_books', '0006_auto_20200527_0121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='digital_book',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authors.Author'),
        ),
    ]
