# Generated by Django 3.0.6 on 2020-06-02 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital_books', '0007_auto_20200527_2137'),
    ]

    operations = [
        migrations.AddField(
            model_name='digital_book',
            name='rating',
            field=models.FloatField(default=0, null=True),
        ),
    ]
