# Generated by Django 3.0.6 on 2020-05-14 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('studyclassrooms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyClassrooms_Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50)),
                ('enter_hour', models.DateField()),
                ('return_hour', models.DateField()),
                ('study_classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studyclassrooms.StudyClassrooom')),
            ],
        ),
    ]
