# Generated by Django 3.0.6 on 2020-06-03 04:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('studyclassrooms_reservations', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studyclassrooms_reservation',
            old_name='enter_hour',
            new_name='devolution_date',
        ),
        migrations.RemoveField(
            model_name='studyclassrooms_reservation',
            name='return_hour',
        ),
        migrations.AddField(
            model_name='studyclassrooms_reservation',
            name='loan_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='studyclassrooms_reservation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
