# Generated by Django 3.0.6 on 2020-05-16 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20200513_0504'),
        ('adquisitions', '0003_collection_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='book',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='books.Book'),
        ),
    ]
