# Generated by Django 3.0.6 on 2020-06-02 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adquisitions', '0011_auto_20200602_0209'),
        ('adquisitions', '0013_auto_20200602_0642'),
    ]

    operations = [
    ]
